### ISSUE TITLE
Make sure balances of accounts when forking are correct

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/ganache-core#128]
For a forked chain to reflect the state of its parent, it needs to map the parent's unlocked accounts onto itself. For example, you would expect

```javascript
const web3 = new Web3(provider);
const parentAccounts = await web3.eth.getAccounts();

const web3 = new Web3(forkedProvider);
const forkedAccounts = await web3.eth.getAccounts();

assert.arraysEqual(parentAccounts, forkedAccounts);
```

This is not currently possible unless you pass ganache a list of private keys (I think).  One hope of the Truffle V5 migrations work is to make `dry-run` a meaningful simulation of the deployment sequence and balance checks are necessarily part of that.  

It's possible we could manage this at truffle where the forking happens by passing in a list of accounts to unlock, setting a high default ether balance, and then running a set of txs that seed the unlocked accounts with the appropriate balances. 

Questions for @seesemichaelj and @benjamincburns:
+ Is this description of how ganache behaves correct?
+ Is managing this at Truffle the right approach? Or is there simpler 5-10 line fix over here?

**Comment by seesemichaelj** [comment]
I updated this issue after talking to @cgewecke some more; it seems that the issue was presented because of the balances were not necessarily matching up in his `dry-run` tests.

This prompted me to look into the issue and found that the fallback `getBalance` method for forked chains was incorrectly converting the balance (i.e. it added `0x` to the beginning of a decimal number string, causing the number to be much larger than it should be)

This issue is not for that bug

**Comment by cgewecke** [comment]
Thanks @seesemichaelj! Great.
