### ISSUE TITLE
Implement EIP-234

### ISSUE THREAD

**Issue by nionis** [trufflesuite/ganache-core#136]
[EIP 234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md)

Adds support to be able to use blockHash in getLogs

already merge on master on both
[geth](https://github.com/ethereum/go-ethereum/pull/16734) and [parity](https://github.com/paritytech/parity-ethereum/pull/9256)

**Comment by fabioberger** [comment]
Happy to work on this now. Has anyone already started?

**Comment by fabioberger** [comment]
Took a gander and looks like the underlying `blockLogs` lookup data-structure (`LevelUpArrayAdapter`) is indexed by `blockNumber`. In order to avoid block re-orgs (e.g snapshots) from causing `getLogs` to return the logs for the incorrect block, we should probably also have a mapping from `blockHash` to `blockLogs`. 

Does this sound correct to the maintainers? @seesemichaelj @benjamincburns @tcoulter

**Comment by seesemichaelj** [comment]
Hey @fabioberger! Nope, no one has started working this (that we know of at least).

Looking at the code, that does sound like a feasible option. I'm going to defer to @davidmurdoch or @benjamincburns on this one. I'll chat with them in our standup today and see if we can get you an answer! Thanks!

**Comment by fabioberger** [comment]
Other things have come up and I haven't found the time to work on this yet. Will chime in again when I find the time. Otherwise, anyone should feel free to take this on.
