### ISSUE TITLE
Wrong request id returned on `eth_subscribe`

### ISSUE THREAD

**Issue by konstantinzolotarev** [trufflesuite/ganache-core#190]
Ganache has issue with 64-bit integers in request id's

After connecting to ganache using websockets and sending `eth_subscribe` command reply contains wrong `id` 

## Current Behavior
```
> {"id":809894640329149302, "jsonrpc": "2.0", "method": "eth_subscribe", "params": ["newHeads", []]}
< {"id":809894640329149300,"jsonrpc":"2.0","result":"0x07"}
```

## Steps to Reproduce (for bugs)
1. Create new folder 
2. Install websocket `npm i ws`
3. Start node.js shell using `node` command.
4. Enter this commands:

```
const WebSocket = require('ws')
const ws = new WebSocket('ws://localhost:7545')
ws.on('message', (data) => console.log(data))
ws.send(JSON.stringify({"id":809894640329149302, "jsonrpc": "2.0", "method": "eth_subscribe", "params": ["newHeads", []]}))

< {"id":809894640329149300,"jsonrpc":"2.0","result":"0x07"}
```

## Context
Couldn't correctly subscribe to ganache ws event.

## Your Environment
* Version used: Ganache CLI v6.1.8 (ganache-core: 2.2.1)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Node.js v 8.12.0
* Operating System and version: MacOS 10.13.5

**Comment by balexander4** [comment]
@konstantinzolotarev Thanks for the detailed reproduction steps, this remains an issue. I have validated that returned id is incorrect with the above reproduction steps.

**Comment by davidmurdoch** [comment]
@konstantinzolotarev  `809894640329149302` is not a valid JavaScript number. In fact, `809894640329149302 === 809894640329149300` evaluates to `true`!

Because the number `809894640329149302` is greater than `Number.MAX_SAFE_INTEGER` the `Number` value is unreliable in JavaScript and you should use it. You _can_ treat it as a `string` in your code, i.e. `"809894640329149302"`, and Ganache will return it correctly in the subscription (as a `string`). If you need to use large numbers like this in JavaScript you should use a library like [BN.js](https://github.com/indutny/bn.js/) (or try [JSBI](https://github.com/GoogleChromeLabs/jsbi), which polyfills the new native BigInt type) and then convert it to and from a string as needed (JSON, which is what Ganache and other Ethereum providers use to communicate, doesn't currently support any number type other than JavaScript's native `Number`, so you'll need to convert to a string first).
