### ISSUE TITLE
Possible msg.data or transaction data regression from v2.3.1 to v2.3.2+

### ISSUE THREAD

**Issue by sohkai** [trufflesuite/ganache-core#283]
It appears there may be a regression related to `msg.data` (opcode: `CALLDATASIZE`) or transaction data-related JSON-RPC behaviour in contracts between v2.3.1 and v2.3.2 of `ganache-core`.

In particular, the following tests failed when upgrading from `ganache-cli@6.2.3` to `ganache-cli@6.2.4-beta.0` and higher, where the only [related thing that changed was the upgrade to `ganache-core` from `2.3.1` to `2.3.2-beta.4`](https://github.com/trufflesuite/ganache-cli/commit/06f242228a2c29c2d3b5b6d91d29d4090506ab99#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R25). The following tests **are** failing on non-beta versions of `ganache-cli@6.2.4` and `ganache-cli@6.2.5` (see [passing CI when pinned to `6.2.3`](https://github.com/aragon/aragonOS/pull/472) and [failing CI when upgraded to `6.2.5`](https://github.com/aragon/aragonOS/pull/471)).

### Test

[Test code](https://github.com/aragon/aragonOS/blob/dev/test/proxy_recover_funds.js#L184)

**What this test checks for**:

We have a [DepositableDelegateProxy](https://github.com/aragon/aragonOS/blob/dev/contracts/common/DepositableDelegateProxy.sol) that allows a sender to send ETH to a delegate proxy if [less than 10k gas and **no data** is sent with the transaction](https://github.com/aragon/aragonOS/blob/dev/contracts/common/DepositableDelegateProxy.sol#L12) (`FWD_GAS_LIMIT ` is defined in a base contract, [DelegateProxy](https://github.com/aragon/aragonOS/blob/dev/contracts/common/DelegateProxy.sol#L8)).

This test tries to assert the data condition: a ETH transfer should fail if data is sent as part of the transaction, even if less than 10k gas is used. On `ganache-cli@6.2.3`, this test passes by causing a revert to occur. However, on `ganache-cli@6.2.4` and higher, the test fails because the transaction completes.

Upon looking into the behaviour (logging both the `gasleft()` and `msg.data` values), it appears that `msg.data` is the culprint; on `ganache-cli@6.2.3`, this test sends a `msg.data` of length `1` whereas on `ganache-cli@6.2.4`, it thinks `msg.data` is of length `0`.

## Expected Behavior

`msg.data` should have the correct data filled in.

## Current Behavior

`msg.data` seems to not have the correct data in recent versions of `ganache-core`.

## Possible Solution

Not sure if it's the `CALLDATASIZE` opcode or a JSON-RPC endpoint. Maybe this was caused due to an undocumented API change (we're using `truffle@4.1.14` so it could be related to how `truffle-contract` expects to send the data although all other transactions except for those sent with `contract.sendTransaction()` seem to work fine).

## Steps to Reproduce (for bugs)

See above

## Context

Would like our tests to pass with newer ganache versions :)

## Your Environment

* Version used: `^6.2.4`
* Operating System and version: macOS 10.14
* Link to your project: https://github.com/aragon/aragonOS

**Comment by davidmurdoch** [comment]
Thanks, @sohkai for filing this issue! It seems like it could be related to some changes made in ganache-core v2.3.2 related to the way we handle transaction data. You could try using `input` instead of `data` when creating the transaction (in your `sendTransaction` call); these two fields are aliases, and I'm wondering if the aliasing isn't working for some reason. Let me know if that works for your or not.

**Comment by sohkai** [comment]
@davidmurdoch I've tried using `input` in https://github.com/aragon/aragonOS/pull/471 but without luck :(.

**Comment by sohkai** [comment]
Just tested with `ganache-cli@6.3.0` (using `ganache-core@2.4.0`) and our tests are still failing.

**Comment by davidmurdoch** [comment]
@sohkai 	thanks for following up. I'll let you know ASAP when a release with the fix has shipped!

**Comment by eshaben** [comment]
Thanks again @sohkai for filing this issue! The PR that addresses this issue has been merged into develop and will be available in our next release, so I am going to go ahead and close this issue.

**Comment by sohkai** [comment]
Looking forward to it @eshaben!

**Comment by davidmurdoch** [comment]
@sohkai The actual bug @eshaben fixed here goes against the JSON-RPC spec in order to match with the behavior shown in geth. Passing `0x1` in a transaction's `data` field is actually invalid; the value should be `0x01` (since it should be an `UNFORMATTED DATA` type). In order to align with geth we now 0 pad these data fields when necessary.

What was happening in ganache-core is that we were creating a native `Buffer` from the given hex value, `"1"`. `Buffer` then checks the length of this value and determines it to be `0`, creates a 0-length Buffer instance, then writes the `"1"` to it, which obviously doesn't work. There is a node issue and comment about `Buffer.from`'s ambiguity here: https://github.com/nodejs/node/issues/8569#issuecomment-316336196, which you may find interesting.

**Comment by sohkai** [comment]
Sounds like we should also update the test to use `0x01` (I just assumed the left padding wouldn't be required, but I can see it also being strict), although node's behaviour is hilariously awful.
