### ISSUE TITLE
Incorrect ChainID in Transaction Hash Serialization

### ISSUE THREAD

**Issue by hayesgm** [trufflesuite/ganache-core#37]
Transaction hashes for submitted transactions incorrectly use `0x1c` (28) as the chain_id, regardless of the actual chain_id. This leads to incorrect transaction hashes being generated / returned via JSON-RPC for `sendRawTransaction` and likely `sendTransaction`.

 

## Expected Behavior

When a transaction is submitted, it should use the correct chain ID when generating the transaction hash according to [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).

Examples transaction in serialized form:

```
[ '0x0',
    '0x09184e72a000',
    '0x0f4240',
    '0x0',
    '0x0',
    '0x0',
    '0x1c', // this should be `chain_id * 2 + 35 + <recovery_bit>`, instead it's hard-coded
    '0x0',
    '0x0' ]
```

## Current Behavior

See above, we're generating the hash from an incorrectly serialized transaction. One could argue that pre-EIP-155 transactions (see the [Yellow Paper](http://yellowpaper.io/) Appendix F), are okay, but we're still not properly encoding the recovery bit (e.g. it should be 27 or 28, not hard-coded at 27). The current behavior is strictly incorrect according to the Ethereum standard.

## Possible Solution

We need to make sure `chain_id` is set when calling `transaction.hash()` after a transaction is submitted via `sendRawTransaction` or `sendTransaction`. This is strictly required to match the official Ethereum specifications for transaction serialization (defined in Eq.(214) and Eq.(215) of the Yellow Paper and EIP-155).

## Steps to Reproduce (for bugs)

1. Generate a valid transaction (T).
2. Build the EIP-155 transaction hash of T ("trx_hash")
3. Serialize T and submit to TestRPC via `sendRawTransaction`
4. Verify that the returned `trx_hash` does not match what was calculated above.

## Context

Transaction hashes must be consistently generated based on input. Otherwise, clients will not be able to check on the status of transactions.

## Your Environment

* Version used: ganache-cli@6.0.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): 
* Server type and version:
* Operating System and version: Darwin 10.12.6
* Link to your project:

**Comment by michiels** [comment]
I might have an error that is related or caused by this, but I'm not sure how further debug.

I'm using `sendRawTransaction` and signing the transaction with the (private) key automatically generated by Ganache. When I try to execute the transaction, it gives an error:

```
IOError: Error: sender doesn't have enough funds to send tx. The upfront cost is: 88000000000000000 and the sender's account only has: 0
```

Sending a regular transaction (not raw/signed) via the first/default account and `sendTransaction` functions works perfectly.

**Comment by mgraczyk** [comment]
The EIP-155 hash is used to determine _what should be signed_. It is not used to identify the transaction in the RPC mechanism. You say 

> We need to make sure chain_id is set when calling transaction.hash() after a transaction is submitted via sendRawTransaction or sendTransaction.

I believe that is not the case. Once a transaction has been submitted via sendRawTransaction and the signature has been verified, the chain_id is irrelevant. The hash of the submitted transaction is just `sha3(serializedTransctionData)`.  Whether or not the transaction's signature is EIP-155 aware does affect the hash computation, only signature verification.

Here's a case using the transaction [here](https://ropsten.etherscan.io/tx/0xe1ba8a320f9fc6846127b244faf9825028d7298c4d34c4aa0fc57d48b85a7ab3).

## Expected Behavior
```bash
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86b808504e3b2920082520894a3bd45f7b000a6d3d2359b0577ed34adbdfc25eb87038d7ea4c68000802aa0dec7e8ff13c93cdc9a75432f01730bdc3a20fc0eaf820a7234c1aabdbf6ccb64a0601845af5cbd02e9c443f870bdbee61c93a5533c4c3f84931a0e1dfab30d39ab"],"id":1}' https://ropsten.infura.io
{"jsonrpc":"2.0","id":1,"result":"0xe1ba8a320f9fc6846127b244faf9825028d7298c4d34c4aa0fc57d48b85a7ab3"}
```

## Current Behaviour
```bash
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86b808504e3b2920082520894a3bd45f7b000a6d3d2359b0577ed34adbdfc25eb87038d7ea4c68000802aa0dec7e8ff13c93cdc9a75432f01730bdc3a20fc0eaf820a7234c1aabdbf6ccb64a0601845af5cbd02e9c443f870bdbee61c93a5533c4c3f84931a0e1dfab30d39ab"],"id":1}' localhost:8545
{"id":1,"jsonrpc":"2.0","result":"0x56860ff2721668edd33f5f86abdbd44fe1a8e8f3efba1a12dc76f2c9da53b836"}
```

Notice that the hash is `0x56860ff2721668edd33f5f86abdbd44fe1a8e8f3efba1a12dc76f2c9da53b836` instead of `sha3(data) = 0xe1ba8a320f9fc6846127b244faf9825028d7298c4d34c4aa0fc57d48b85a7ab3`

## Solution
Always use `sha3(rawData)` to identify signed transactions json rpc.

## Steps to reproduce
Using `Ganache CLI v7.0.0-beta.0 (ganache-core: 3.0.0-beta.0)`:

Run gananche-cli in the background using this:
```javascript
const secretKey = Buffer.from('8874F01D72E7BE5D5417B55E0F21698692704F408C1AFF382641DB0423F1B2E1', "hex");
const config = {
  "accounts": [
    { "balance": 1000000 * 1000000000000000000,
      "secretKey": secretKey
    }, ], };

require("ganache-cli").server(config).listen(8545);
```

Then run curl as above.

**Comment by mgraczyk** [comment]
The transaction hash should not depend on ChainID. See #56 for details.

**Comment by davidmurdoch** [comment]
Closing as this is an old issue and I believe it has been fixed for a while now. If it is still an issue for you, please open a new issue with the details. Thanks!
