### ISSUE TITLE
6.4.2: `TypeError: Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by tyler17** [trufflesuite/ganache-core#417]
## Expected Behavior
ganache-cli not crashing
## Current Behavior
After upgrading to v6.4.2 (from v6.2.5), the testchain will randomly crash in the middle of our tests with 
```
eth_blockNumber
eth_blockNumber
eth_blockNumber
TypeError: Cannot read property '0' of undefined
    at e (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5393)
    at u (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5429)
    at u (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5955)
    at u (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:5770)
    at /Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:4169
    at /Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1861552
    at /Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124
    at i (/Users/Tyler/dai.js/testchain/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:41179)
```

## Steps to Reproduce
checkout branch `sdk-688` here: https://github.com/makerdao/dai.js/tree/sdk-688
follow steps under `Developing` in Readme
run tests with `yarn test`

## Your Environment
* Version used: 6.4.2
* NodeJS Version: v10.13.0
* Operating System and version: macOS High Sierra, version 10.13.4 Beta
* Link to your project or repro gist: https://github.com/makerdao/dai.js/tree/sdk-688
* Commit hash to use with above link for reproduction: 7a246d18b91f259bb9e3f9ec1a064fba96ab9619

**Comment by davidmurdoch** [comment]
For our internal reference, here is the potential fix: https://github.com/trufflesuite/ganache-core/commit/b74050bd5505b92fcc123affb52108c4c5b3004b

**Comment by ndeshev** [comment]
Hey there guys, I apologize for the delayed response. Unfortunately, at this stage I'm not able to provide the code producing the errors, I will try to help by describing more of my observations using and testing the  6.4.3 version with the latest MM and web3.js (1.00-beta.52) for multi-contract (10+) contract Dapp, during the last few days.

- If default gas or the gas option for the contract call is set in web3 (like `myContract.methods.myMethod([param1[, param2[, ...]]]).send( { from: '0x0', gas: 1234 })`) the ganache does not break, probably because MetaMask gets the the gas values directly and never requests eth_estimateGas to the function call
 
- In my comment above I said that the only functions that did not break the client are the simple ones - after more tests that turned out to not be the case as some of the bigger ones (400k+ gas required) also do not break it, it only happens to a handful of function calls. 

- The higher the gas limit for the block is set - the higher the estimated gas required for the call is, for example, if the block gas limit is 8M the estimated gas for the call is 100k, if the block gas limit is 80M the estimation is 800K (example values)

Note: All calls are going through multiple contracts, meaning: call to an entry contract - > that calls a logic contract -> that calls storage contract.

**Comment by tyler17** [comment]
@davidmurdoch Awesome, just wanted to confirm that I tried using that `fix/gas-est-crash` branch locally and I'm not getting crashes anymore

**Comment by ndeshev** [comment]
Confirming that the potential fix resolves the client crashing during UI testing with MM & web3.js. All other gas estimation problems described in #issuecomment-484739359 are the same. 
Mainly: The gas estimates are way overestimated, 2x and 3x the actual amount required. The block gas limit has a very strange increasing/decreasing effect on it.

**Comment by davidmurdoch** [comment]
Thanks @ndeshev for following up. I wasn't able to reproduce the crash with the contract examples you provided since they are incomplete contracts. I'm hesitant to release this patch without a test to ensure we don't regress in the future. Is there any chance you can provide us with a complete reproduction contract.

The overestimate is definitely a separate bug. @nicholasjpaterno will likely be looking into this issue when he wraps up some of his current tasks. Changing the `blockGasLimit` having an effect on estimation isn't too surprising (probably still a bug if we are returning fluctuating gas estimates), as many contract functions do require additional gas the more gas you provide (we use the `blockGasLimit` as the default `gas` amount in our gas estimate calculations). See [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md) (specifically the EIP-114 proposal it implements) for details.

There is one edge case we do know about and don't try to handle: when a contract checks its gasLeft and behaves differently depending on this value. A contrived example being:

```
  if (gasLeft % 2 == 0) {
     expensive();  
  } else {
    cheap();
  }
```

A function like the above would cause gas estimations to vary wildly depending on the amount of gas initially supplied to the transaction.

---

Just to reiterate: the amount of gas _required_ is often greater than the amount of gas _used_. Any chance you could provide a minimal reproduction of a fluctuating and wildly high gas estimate contracts?

**Comment by tyler17** [comment]
@davidmurdoch Are you still unable to reproduce the crash? I'm finding that it crashes with some (but not all) calls made to [DS Proxy's execute function](https://github.com/dapphub/ds-proxy/blob/master/src/proxy.sol), maybe the delegatecall is causing the issue?

**Comment by davidmurdoch** [comment]
Thanks @tyler17! Yes, we're still looking for a minimal reproduction of the issue. This line looks like great candidate to produce an edge case in opcode ordering we don't handle: https://github.com/dapphub/ds-proxy/blob/379f5e2fc0a6ed5a7a96d3f211cc5ed8761baf00/src/proxy.sol#L64

@nicholasjpaterno :point_up:

**Comment by sirpy** [comment]
@davidmurdoch This still happens in beta 2.5.6. on eth_estimateGas
It happens when trying to execute an erc 677 transferAndCall.
If I set the gas to fixed amount (200000) it works fine otherwise ganache crashes with the above error right after eth_estimateGas

The client code is in this method:
https://github.com/GoodDollar/GoodDAPP/blob/33b78201078fe72604d23a5a8a867ca6fd245e31/src/lib/wallet/GoodWallet.js#L402

The contracts code is here:
ERC677 - https://github.com/GoodDollar/GoodContracts/blob/47079ad5005526f204760b9c1b47fcd9ad04515d/contracts/GoodDollar.sol#L94

The called method after transfer
https://github.com/GoodDollar/GoodContracts/blob/47079ad5005526f204760b9c1b47fcd9ad04515d/contracts/OneTimePaymentLinks.sol#L50
