### ISSUE TITLE
BUG: not possible to delete storage on forked chain

### ISSUE THREAD

**Issue by thegostep** [trufflesuite/ganache-core#446]
## Expected Behavior

Using a fork of mainnet, ganache should be able to set storage variables to 0.

## Current Behavior

Ganache is able to set storage variables to any value except 0. If an attempt is made to set the storage variable to 0, it will skip the instruction and continue execution as if successful.

## Possible Solution

unknown

## Steps to Reproduce (for bugs)
1. Deploy a contract with non-zero storage value
2. Fork into ganache
3. Attempt to set storage value to zero
4. Use a getter or event to check that it failed

## Context

Forked chains should support setting storage values to zero.

## Your Environment
* Version used: 6.4.2, v6.4.4-beta.0
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): macOS

**Comment by niklasb** [comment]
I thought about this a bit more and it should not be hard to implement this fix: We would just need to store one extra flag in the trie nodes indicating whether the node has been deleted. .del() sets this bit to true, .put() sets it to false. In case a node exists in the ForkedStorageBaseTrie, .get()/.hasKey() etc. should use this bit instead of falling back to the upstream RPC.

**Comment by niklasb** [comment]
@davidmurdoch what is the status on this? is help required?
