### ISSUE TITLE
chainId inconsistencies

### ISSUE THREAD

**Issue by Amxx** [trufflesuite/ganache-core#582]
Current behaviour:

Just start ganache-cli:
- `web3.eth.net.getId()` returns `1591977484336`
- the `chainId` opcode (EIP1334) returns `1`
- the `eth_chainId` RPC call returns `0x539` (1337)

Expected behaviour:
- some consistency

**Comment by davidmurdoch** [comment]
Thanks for reporting. Closing as this issue is being tracked by https://github.com/trufflesuite/ganache-core/issues/515, https://github.com/trufflesuite/ganache-core/issues/557, and 
https://github.com/trufflesuite/ganache-core/issues/575. The issue will be fixed in v3, tracked by https://github.com/trufflesuite/ganache-core/issues/451, milestone: https://github.com/trufflesuite/ganache-core/milestone/1.
