### ISSUE TITLE
Ability to specify zero accounts created/unlocked

### ISSUE THREAD

**Issue by jstoxrocky** [trufflesuite/ganache-core#60]
## Expected Behavior
I would like to be able to specify zero accounts created/unlocked when starting ganache.

## Current Behavior
Setting` options = { total_accounts: 0 }` does not work as it will default to 10 accounts if set to `0` due to this line: https://github.com/trufflesuite/ganache-core/blob/develop/lib/statemanager.js#L42.

## Context
I am trying to test situations where a user signs out of MetaMask. If a user goes from a logged-in state to a logged-out state in MetaMask, the web3 object persists in the browser but the number of unlocked accounts available goes to zero. I would like to be able to test this behaviour in my code.

**Comment by davidmurdoch** [comment]
@jstoxrocky I know it's been a long time since you've open the issue (sorry about that!). If the user specifies no accounts there can't be a `coinbase` account --  which is the account that mines the blocks. I was thinking we could just use the `0x0` account as the default coinbase account.

Do you have any thoughts?

**Comment by eggplantzzz** [comment]
work for this in #817
