### ISSUE TITLE
Bad gas estimate returned for functions with `gasLeft()`

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/ganache-core#617]
## Current Behavior

Running `eth_estimateGas` on a function which contains `gasLeft()` operation returns vastly overestimated value.

## Steps to Reproduce (for bugs)
You can see the large estimates reported when you run the selected tests here:
https://github.com/argentlabs/argent-contracts/tree/experiment/better-gas-estimation

I added a `GasEstimation` contract and tests to try and isolate the issue with no success. It is clear however from the other failing tests that `gasleft()` is causing the issue as when removed [here](https://github.com/argentlabs/argent-contracts/blob/experiment/better-gas-estimation/contracts/modules/RelayerModule.sol#L104) gas estimations become near spot on correct.

## Your Environment
* Version used: `ganache-cli@6.9.1`
* Operating System and version: OSx
* Link to your project: https://github.com/argentlabs/argent-contracts

**Comment by elenadimitrova** [comment]
Maybe related https://github.com/ethereum/EIPs/pull/2075

**Comment by davidmurdoch** [comment]
This is likely caused by the fact that `estimateGas` requires an upper bound when estimating  (we use `Number.MAX_SAFE_INTEGER`). If the contract changes its behavior based on the amount of gas left (which this contract appears to do) then we can't actually generate an accurate estimate, as the gas used may actually depend on amount of gas initially provided.

One thing you can do, assuming this isn't a bug, is include your own `gasLimit` in your `estimateGas` calls in order to manually control this upper bound.

Can you try that out and let me know if things start making sense?

**Comment by elenadimitrova** [comment]
Thanks @davidmurdoch I noticed `estimateGas` was always returning numbers around and just over the `gasLimit` (here I mean the `gasLimit` parameter of `execute` function rather than the overall transaction gasLimit). However when using a low value for that, e.g. `1`, the estimation returned is correct. So we'll just go down that route.
