### ISSUE TITLE
Chain Reorganization Support

### ISSUE THREAD

**Issue by Troublor** [trufflesuite/ganache-core#646]
Chain reorganization is an important feature and I want to test whether my DApp can handle this properly using Ganache. 
However, it seems Ganache does not support simulate the chain reorg behaviour by now. 

One workaround is to set up a blockchain cluster with multiple nodes, but it seems Ganache also does not support establishing a cluster (from [this](https://ethereum.stackexchange.com/questions/51572/is-it-possible-to-run-multiple-ganache-nodes-for-private-test-network) StachExchange). 

I find #91 discussing chain reorg features but it has been two years and no further activities in that issue. 

Is it possible for Ganache to provide a JSON-RPC method `eth_reorg` similar to `evm_revert` to simulate the blockchain reorganization? 

 

## Expected Behavior

A new RPC method used to trigger a blockchain reorganization in Ganache's underlying blockchain. 

## Current Behavior

Ganache currently cannot simulate blockchain reorganization hehaviours.

**Comment by davidmurdoch** [comment]
Thanks for bringing this up, though I don't see any reason to track this feature in two separate issues, so I'm closing this in favor of #91. If you want to be kept apprised of any progress you can comment or subscribe to that issue.

Since you mentioned adding a new rpc method to trigger `changed` events, which would be part of the solution, in addition to `newHeads`. There is a similar issue suggesting using `evm_revert` itself for this: https://github.com/trufflesuite/ganache-core/issues/411
