### ISSUE TITLE
Tx hash invalid

### ISSUE THREAD

**Issue by julesGoullee** [trufflesuite/ganache-core#66]
I trying to simplify the situation but I cannot reproduce more simple:
I'm using account with default balance (with auto mine on every transaction), send 1 eth to one address, 1 eth to an other address, and form this two address two transaction on an other.  
<img width="755" alt="capture d ecran 2018-02-12 a 03 49 26" src="https://user-images.githubusercontent.com/6892100/36082239-f2ed234c-0fa7-11e8-98ef-c93c0257569f.png">

The bug is tx 3 et 4 in my schema have the same tx hash, wallet 3 have right balance (tx 3 + tx 4) when I call getBlock with web 3 I find one ( and bug is same) tx in two last block. This bug appear only if tx3 and 4 have the same amount, if it's different value hash is correct.

**Comment by beether** [comment]
This is a known bug, but I don't know where the issue for it is. TX hashes are built from some of the tx params -- if you use the exact same params you'll get hash collisions and weird stuff will happen. As far as I know, this only happens if the transactions are on the same block... so I don't quite believe you have "automine" enabled.

Anyway, the workaround is to provide different "gas" amounts for your identical same-block transactions.

**Comment by seesemichaelj** [comment]
This was fixed sometime. We have tests to cover this issue. If you're still having problems, please open a new issue. Thanks for reporting!
