### ISSUE TITLE
Successfully use Filecoin Shipyard's Filecoin Pickaxe with CLI

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#695]

**Comment by mikeseese** [comment]
I'm deciding to move forward without testing this example. This is because it uses https://github.com/jimpick/filecoin-pickaxe-mineshaft/blob/master/mineshaft.js which boots up it's own IPFS instance and tries to sync/collaborate with the IPFS network. It would be an essential rewrite to support Ganache
