### ISSUE TITLE
Successfully use Filecoin Shipyard's Meme Marketplace with CLI

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#697]

**Comment by mikeseese** [comment]
Hard brakes on this one! This should technically be possible by spooling up the Textile services:
- `powergate` (without IPFS or Lotus)
- Textile `buckd`
- Textile `hubd`

and connect them to the Ganache IPFS and Lotus simulators. However, powergate alone is going to require supporting many more RPC methods, and it's also very likely going to require cryptographic integrity and other things that are going to look like a *real* Lotus node/VM simulator

I think supporting a Textile workflow that supports a Ganache backend rather than a real Lotus + IPFS backend would be pretty cool, but this is out of scope for now
