### ISSUE TITLE
Custom Provider with #parity_listStorageKeys

### ISSUE THREAD

**Issue by Latrasis** [trufflesuite/ganache-core#96]
## Context
When debugging or accessing storage within an account, it is valuable to see all the storage keys used within an account's state tree. Currently this is solved with injecting logs into a contract, this however makes development cumbersome and is not possible with already compiled contracts.

## Expected Behavior
The Parity JSONRPC Api includes [#parity_liststorageKeys](https://wiki.parity.io/-parity-module#parity_liststoragekeys) which lists all used storage keys of an account.
This is incredibly useful for debugging purposes and can be opt-in with a flag. `--fat-db`

## Current Behavior
Ganache-core currently does not provide any way to list account storage keys when debugging

## Possible Solution
Include a custom provider which exposes a subset of parity json-abi calls for debugging, starting from: `#parity_liststorageKeys`.

## Environment
* Version used 2.1.0
* Operating System and Version: WSL Bash

**Comment by seesemichaelj** [comment]
Hey @Latrasis! This does sound like an interesting feature, but I think you could use `debug_traceTransaction` and/or use the Truffle Debugger to help with these kinds of things rather than implementing these features within ganache.

We don't have any plans to implement this unfortunately. Thanks for the suggestion however!
